# Generated by Django 4.2.13 on 2024-06-09 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_alter_medcard_patient_metrick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bypass', models.CharField(blank=True, max_length=500, null=True)),
                ('complaints', models.CharField(blank=True, max_length=500, null=True)),
                ('medical_history', models.CharField(blank=True, max_length=500, null=True)),
                ('anamnesis_of_life', models.CharField(blank=True, max_length=500, null=True)),
                ('allergic_history', models.CharField(blank=True, max_length=500, null=True)),
                ('transfusion_history', models.CharField(blank=True, max_length=500, null=True)),
                ('objective_examination_data', models.CharField(blank=True, max_length=500, null=True)),
                ('is_examined_on_an_outpatient_basis', models.BooleanField(default=False)),
                ('examination_plan', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_plan', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('med_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medcard')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
