# Generated by Django 4.2.13 on 2024-06-10 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient_initial_examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialexamination',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
