# Generated by Django 4.2.13 on 2024-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_initial_examination', '0002_initialexamination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialexamination',
            name='is_examined_on_an_outpatient_basis',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False),
        ),
    ]
