# Generated by Django 4.2.13 on 2024-06-10 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0004_remove_medcard_additional_patient_metrick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('p', 'Предварительный'), ('c', 'Клинический'), ('f', 'Окончательный')], max_length=1, null=True)),
                ('types', models.CharField(blank=True, choices=[('main', 'Основное'), ('сopg', 'Конкурирующее'), ('back', 'Фоновое'), ('copn', 'Осложнение')], max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_diagnoses.diagnosesname')),
                ('med_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.medcard')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
