# Generated by Django 4.2.13 on 2024-06-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_diagnoses', '0002_diagnoses_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnoses',
            old_name='types',
            new_name='type',
        ),
    ]
