# Generated by Django 4.2.13 on 2024-06-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_diagnoses', '0003_rename_types_diagnoses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoses',
            name='kind',
            field=models.CharField(blank=True, choices=[('pr', 'Предварительный'), ('cl', 'Клинический'), ('fi', 'Окончательный'), ('pa', 'Патологоанатомический'), ('st', 'Этапный')], max_length=2, null=True),
        ),
    ]
