# Generated by Django 4.2.13 on 2024-06-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_alter_medcard_patient_metrick'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50)),
                ('indicator_norm', models.CharField(blank=True, max_length=50, null=True)),
                ('indicator_unit', models.CharField(blank=True, max_length=25, null=True)),
                ('analysis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_analysis.analysisname')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('status', models.CharField(choices=[('Принят на работу', 'Pending'), ('Завершен', 'Completed')], default='pending', max_length=16)),
                ('analysis_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_analysis.analysisname')),
                ('med_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medcard')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_result', models.CharField(max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_analysis.analysis')),
                ('analysis_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_analysis.analysisindicator')),
            ],
            options={
                'unique_together': {('analysis', 'analysis_indicator')},
            },
        ),
    ]
