# Generated by Django 4.2.13 on 2024-06-03 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('iin', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('Ж', 'Женщина')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('med_card_status', models.CharField(choices=[('o', 'Открыта'), ('c', 'Закрыта')], max_length=7)),
                ('med_card_number', models.CharField(max_length=4)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('temperatury', models.CharField(max_length=4)),
                ('puls', models.CharField(max_length=4)),
                ('resperatory_rate', models.CharField(max_length=3)),
                ('pressure', models.CharField(max_length=7)),
                ('saturation', models.CharField(max_length=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalPatientMetrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(default='-', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Additional_patient_metrick', to='patient.patient')),
            ],
        ),
    ]
