# Generated by Django 4.2.13 on 2024-06-07 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_department_id_department_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('E', 'Экстренное (Первые 6 часов)'), ('M', 'Первые 24 часа'), ('P', 'Плановое')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMetrick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('temperatury', models.CharField(max_length=4)),
                ('puls', models.CharField(max_length=4)),
                ('resperatory_rate', models.CharField(max_length=3)),
                ('pressure', models.CharField(max_length=7)),
                ('saturation', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='additionalpatientmetrick',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_card_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='med_card_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='puls',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='receipt_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='resperatory_rate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='saturation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='temperatury',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.CreateModel(
            name='MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_card_number', models.CharField(max_length=4)),
                ('med_card_status', models.CharField(choices=[('o', 'Открыта'), ('c', 'Закрыта')], max_length=7)),
                ('additional_patient_metrick', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.additionalpatientmetrick')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('patient_metrick', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmetrick')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reanimation', models.BooleanField()),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_discharge', models.DateTimeField(null=True)),
                ('department', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
                ('doctor', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finance_source', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.financesource')),
                ('hospitalization_type', models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.hospitalizationtype')),
                ('med_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medcard')),
            ],
        ),
    ]
