# Generated by Django 4.2.13 on 2024-06-02 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='med_card_number',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pressure',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='patient',
            name='puls',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='patient',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='resperatory_rate',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='saturation',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='temperatury',
            field=models.CharField(max_length=4),
        ),
    ]
