# Generated by Django 4.2.13 on 2024-06-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_hospitalization_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcard',
            name='patient_metrick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patientmetrick'),
        ),
    ]
