# Generated by Django 4.2.13 on 2024-06-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_medcard_patient_metrick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcard',
            name='additional_patient_metrick',
        ),
        migrations.AddField(
            model_name='additionalpatientmetrick',
            name='med_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.medcard'),
            preserve_default=False,
        ),
    ]
