# Generated by Django 4.2.13 on 2024-06-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patientmetrick_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmetrick',
            name='patient',
        ),
    ]
