# Generated by Django 4.2.13 on 2024-06-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_remove_patientmetrick_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmetrick',
            name='med_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.medcard'),
        ),
    ]
