# Generated by Django 4.2.13 on 2024-06-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patientmetrick_med_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='reanimation',
            field=models.BooleanField(choices=[('reanimation', True), ('not_in_reanimation', False)]),
        ),
    ]
