# Generated by Django 4.2.13 on 2024-06-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_alter_hospitalization_reanimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='reanimation',
            field=models.BooleanField(choices=[(True, 'В реанимации'), (False, 'Не в реанимации')]),
        ),
    ]
