# Generated by Django 4.2.13 on 2024-06-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=50)),
                ('indicator_norm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_result', models.CharField(max_length=50)),
                ('analysis_indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_analysis.analysisindicator')),
                ('analysis_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_analysis.analysisname')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
