# Generated by Django 4.2.13 on 2024-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_analysis', '0002_analysisindicator_analysis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisindicator',
            name='indicator_unit',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
