# Generated by Django 4.2.13 on 2024-06-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_hospitalization_department_id_and_more'),
        ('patients_analysis', '0004_alter_analysisindicator_indicator_norm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisindicator',
            old_name='analysis_id',
            new_name='analysis_name_id',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='analysis_name_id',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='patient_id',
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField()),
                ('status', models.CharField(choices=[('Принят на работу', 'Pending'), ('Завершен', 'Completed')], default='pending', max_length=16)),
                ('analysis_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients_analysis.analysisname')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients_analysis.analysis'),
            preserve_default=False,
        ),
    ]
