# Generated by Django 4.2.13 on 2024-06-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_analysis', '0005_rename_analysis_id_analysisindicator_analysis_name_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analysis_name_id',
            new_name='analysis_name',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='analysisindicator',
            old_name='analysis_name_id',
            new_name='analysis_name',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='analysis_id',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='analysis_indicator_id',
            new_name='analysis_indicator',
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('analysis', 'analysis_indicator')},
        ),
    ]
