# Generated by Django 4.2.13 on 2024-06-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_hospitalization_department_id_and_more'),
        ('patients_analysis', '0006_rename_analysis_name_id_analysis_analysis_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='med_card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.medcard'),
            preserve_default=False,
        ),
    ]
